# Generated by Django 3.2.9 on 2021-11-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations_app', '0002_donation_institution_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
